name: Daily Prerelease

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get version from script and append -pre
        id: get_version
        run: |
          version=$(grep -Po '\$scriptVersion\s*=\s*"\K[^"]+' appinstaller.ps1)
          version_pre="${version}-pre"
          echo "version_pre=$version_pre" >> $GITHUB_OUTPUT

      - name: Create prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version_pre }}
          name: Pre-release ${{ steps.get_version.outputs.version_pre }}
          prerelease: true
          body: |
            > [!WARNING] **This is an automated daily pre-release and may not function correctly!**
            
            These builds are for testing and validation. Use the [weekly release](https://github.com/DeisDev/AppInstaller/releases) for stable usage.

            ## Run without downloading

            > [!TIP] To run directly from GitHub in an elevated PowerShell prompt:

            ```powershell
            irm https://raw.githubusercontent.com/DeisDev/AppInstaller/main/appinstaller.ps1 | iex
            ```

            Or, using `Invoke-WebRequest`:

            ```powershell
            iwr https://raw.githubusercontent.com/DeisDev/AppInstaller/main/appinstaller.ps1 -UseBasicParsing | iex
            ```

            ---
            _Automated daily pre-release for development/testing purposes._
          files: appinstaller.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}