name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get version from script
        id: get_version
        run: |
          version=$(grep -Po '\$scriptVersion\s*=\s*"\K[^"]+' appinstaller.ps1)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            This is release ${{ steps.get_version.outputs.version }} of the appinstaller.ps1 script.

            See the repository for usage instructions and details.
          files: appinstaller.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}